name: Augur Handbook
favicon: null
layout_spectrum: 0.98377
typography_spectrum: 0.00901
title: Augur Handbook
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#63254f'
    - '#000000'
    - '#ff0000'
    - '#00ff00'
    - '#ffffff'
  brandStrength: 0.5
  lightness: 0.9399920939467847
  saturation: 0.4420229457318783
  rhythmicContrast: 0.2314580928068608
purpose: []
