name: Augur Handbook
favicon: null
layout_spectrum: 0.89039
typography_spectrum: 0.5
title: Augur Handbook
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#63254f'
    - '#000000'
    - '#ff0000'
    - '#550000'
    - '#00ff00'
  brandStrength: 0.5
  lightness: 0.8125
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
